In [1]:
#import matplotlib.pyplot as plt
#import seaborn as sns


import pandas as pd
import numpy as np
import random as rnd

from sklearn.cross_validation import KFold, cross_val_score

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier



train_=pd.read_csv('../final.csv')
validate_=pd.read_csv('../validate_allcols.csv')
#test=pd.read_csv('../testwDSM.csv')

characters = pd.read_csv('chars.csv', sep=',')

train_.shape, validate_.shape, #test.shape

/Users/arc/Codes/DM-Lab/dmlab/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


((301619, 62), (148560, 62))

In [2]:
characters.shape


(9, 63)

In [4]:
train = train_.query('DSMCRIT > 13 and DSMCRIT < 20')
validate = validate_.query('DSMCRIT > 13 and DSMCRIT < 20')
#print train['DSMCRIT'].value_counts()
print train.shape

(3131, 62)


In [5]:
#alcohol
#print train['DSMCRIT'].value_counts() / train['DSMCRIT'].count()
#print train['SUB1'].value_counts() / train['SUB1'].count()

In [6]:
#train.query('SUB1 == 4')['DSMCRIT'].value_counts() / train.query('SUB1 == 4')['DSMCRIT'].count()

In [7]:
#train.describe()
#train = train.sample(20000)
#validate = validate.sample(6000)
train.shape, #validate.shape, #validate.head(2)

((3131, 62),)

In [8]:
#train = train.query('SUB1 <= 10').query('SUB2 <= 10')
#validate = validate.query('SUB1 <= 10').query('SUB2 <= 10')

drop_list = ['DSMCRIT',  #'NUMSUBS'
             ]
drop_list_select = ['RACE', 'PREG', 'ARRESTS', 'PSYPROB', 'DETNLF', 'ETHNIC', 'MARSTAT', 'GENDER', 'EDUC'
                   ,'LIVARAG', 'EMPLOY', 'SUB3']

retain_list = ['RACE','PCPFLG','PRIMINC','LIVARAG','BENZFLG','HLTHINS','GENDER','ROUTE3','PRIMPAY',
               'MARSTAT','PSYPROB','ROUTE2','EMPLOY','SUB2','FRSTUSE3','FREQ3','FRSTUSE2','OTHERFLG',
               'EDUC','FREQ2','FREQ1','YEAR',
               'PSOURCE','DETCRIM','DIVISION','REGION','NOPRIOR','NUMSUBS','ALCDRUG',
               'METHUSE','FRSTUSE1','AGE','COKEFLG','OPSYNFLG','IDU','SERVSETA','ROUTE1','MARFLG',
               'MTHAMFLG','HERFLG',
               'ALCFLG','SUB1']
X_train = train[retain_list]

X_c = characters[retain_list]
Y_c = characters["DSMCRIT"]
#X_train = train.drop(drop_list + drop_list_select, axis=1)
Y_train = train["DSMCRIT"]
#X_validate = validate.drop(drop_list + drop_list_select, axis=1)
#Y_validate = validate["DSMCRIT"]
#X_test  = test.drop(drop_list, axis=1)
X_train.shape, #X_validate.shape, #X_test.shape



((3131, 42),)

In [9]:
print X_c.shape

(9, 42)


In [10]:
print X_train.columns.tolist()

['RACE', 'PCPFLG', 'PRIMINC', 'LIVARAG', 'BENZFLG', 'HLTHINS', 'GENDER', 'ROUTE3', 'PRIMPAY', 'MARSTAT', 'PSYPROB', 'ROUTE2', 'EMPLOY', 'SUB2', 'FRSTUSE3', 'FREQ3', 'FRSTUSE2', 'OTHERFLG', 'EDUC', 'FREQ2', 'FREQ1', 'YEAR', 'PSOURCE', 'DETCRIM', 'DIVISION', 'REGION', 'NOPRIOR', 'NUMSUBS', 'ALCDRUG', 'METHUSE', 'FRSTUSE1', 'AGE', 'COKEFLG', 'OPSYNFLG', 'IDU', 'SERVSETA', 'ROUTE1', 'MARFLG', 'MTHAMFLG', 'HERFLG', 'ALCFLG', 'SUB1']


In [11]:
from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.feature_selection import f_classif,chi2
#Selector_f = SelectPercentile(f_classif, percentile=25)
Selector_f = SelectKBest(f_classif, k=10)
Selector_f.fit(X_train,Y_train)

zipped = zip(X_train.columns.tolist(),Selector_f.scores_)
ans = sorted(zipped, key=lambda x: x[1])
for n,s in ans:
     print 'F-score: %3.2ft for feature %s' % (s,n)
        
        
#X_train= SelectKBest(f_classif, k=10).fit_transform(X_train, Y_train)


F-score: 2.53t for feature PCPFLG
F-score: 3.89t for feature PSOURCE
F-score: 5.77t for feature FREQ1
F-score: 6.16t for feature SUB2
F-score: 6.66t for feature METHUSE
F-score: 9.42t for feature OPSYNFLG
F-score: 9.57t for feature BENZFLG
F-score: 9.63t for feature YEAR
F-score: 9.73t for feature HERFLG
F-score: 10.22t for feature FREQ2
F-score: 12.84t for feature ROUTE2
F-score: 14.31t for feature ROUTE3
F-score: 14.41t for feature RACE
F-score: 14.58t for feature FREQ3
F-score: 14.65t for feature PRIMINC
F-score: 15.44t for feature IDU
F-score: 16.21t for feature MARSTAT
F-score: 16.45t for feature REGION
F-score: 17.43t for feature DETCRIM
F-score: 18.15t for feature HLTHINS
F-score: 19.06t for feature SERVSETA
F-score: 21.26t for feature ALCFLG
F-score: 21.36t for feature GENDER
F-score: 22.36t for feature MARFLG
F-score: 22.45t for feature FRSTUSE3
F-score: 23.28t for feature ALCDRUG
F-score: 24.55t for feature FRSTUSE2
F-score: 25.54t for feature FRSTUSE1
F-score: 25.74t for fea

In [12]:
#one hot
from sklearn import preprocessing

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(X_train)

# 3. Transform
onehotlabels = enc.transform(X_train).toarray()
X_train = onehotlabels

#onehotlabels = enc.transform(X_validate).toarray()
#X_validate = onehotlabels


X_char = enc.transform(X_c).toarray()

print X_train.shape, X_char.shape#X_validate.shape

(3131, 236) (9, 236)


In [13]:
#kfold
kf = 3

In [14]:
# Logistic Regression
logreg = LogisticRegression(n_jobs=-1)
logreg.fit(X_train, Y_train)
#Y_pred = logreg.predict(X_test)

l_acc_log = cross_val_score(logreg, X_train, Y_train, cv=kf)
acc_log = round(np.mean(l_acc_log), 3)

l_acc_log = ['%.3f' % elem for elem in l_acc_log]
print l_acc_log
print acc_log

/Users/arc/Codes/DM-Lab/dmlab/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


['0.444', '0.470', '0.469']
0.461


In [22]:
yp_char = logreg.predict_proba(X_char)
print yp_char
#print Y_c

[[  1.11497393e-01   3.44899754e-01   5.63947662e-02   4.74058564e-01
    2.20625146e-04   1.29288973e-02]
 [  9.51721945e-03   1.55317058e-01   1.57720953e-02   2.23074862e-02
    7.94390173e-02   7.17647124e-01]
 [  1.69772242e-02   8.22606606e-01   2.27405509e-02   1.33518134e-01
    4.38697271e-04   3.71878725e-03]
 [  1.73981752e-01   3.50556723e-01   7.04990871e-02   1.59012384e-01
    2.36240034e-02   2.22326051e-01]
 [  2.85981447e-02   9.06358954e-02   1.40012108e-01   6.36032589e-01
    4.00034563e-03   1.00720917e-01]
 [  2.19449452e-01   3.02814671e-01   1.26910573e-01   1.06201794e-01
    1.02496755e-02   2.34373834e-01]
 [  2.55422163e-02   4.73246339e-01   8.87420907e-02   2.35579856e-01
    1.35415386e-03   1.75535344e-01]
 [  1.98986312e-02   6.73535283e-01   1.92076866e-02   1.28788862e-01
    2.39269813e-03   1.56176839e-01]
 [  3.01008717e-03   1.50552538e-01   9.35979738e-02   1.11376845e-02
    6.87801732e-03   7.34823699e-01]]


In [15]:
# Random Forest (slow)

random_forest = RandomForestClassifier(n_estimators=200, max_depth=20, n_jobs=-1)
random_forest.fit(X_train, Y_train)
#Y_pred = random_forest.predict(X_test)

l_acc_random_forest = cross_val_score(random_forest, X_train, Y_train, cv=kf)
acc_random_forest = round(np.mean(l_acc_random_forest), 3)

l_acc_random_forest = ['%.3f' % elem for elem in l_acc_random_forest]
print l_acc_random_forest
print acc_random_forest

['0.508', '0.491', '0.505']
0.501


In [21]:
yp_char = random_forest.predict_proba(X_char)
print yp_char
#print Y_c

[[ 0.14530757  0.3240883   0.05048409  0.41144511  0.00765768  0.06101726]
 [ 0.11286252  0.2285624   0.13814668  0.15867911  0.12126695  0.24048234]
 [ 0.07164716  0.46387738  0.16199469  0.2158646   0.02054503  0.06607113]
 [ 0.20276941  0.2455401   0.07586308  0.33659791  0.00823168  0.13099783]
 [ 0.07552632  0.16587149  0.24046533  0.43202575  0.025       0.06111111]
 [ 0.23775227  0.30754384  0.05690268  0.28421643  0.0225303   0.09105449]
 [ 0.14687374  0.31478455  0.1132663   0.27888247  0.02062437  0.12556856]
 [ 0.09517551  0.45206847  0.10951594  0.19380366  0.02292808  0.12650834]
 [ 0.08469188  0.29368347  0.14868347  0.10558824  0.04        0.32735294]]
