In [20]:
#visualization part
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font_scale=1)
plt.style.use('ggplot')

#import csv from the dataset
import pandas as pd
import numpy as np
import random as rnd

from sklearn.model_selection import cross_val_score

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier



train=pd.read_csv('../train.csv')
validate=pd.read_csv('../validate.csv')
#test=pd.read_csv('../testwDSM.csv')

train.shape, validate.shape, #test.shape

((1508933, 48), (743207, 48))

In [21]:
#train.describe()
train = train.head(20000)
validate = validate.head(6000)
train.shape

(20000, 48)

In [22]:
#train = train.query('SUB1 <= 10').query('SUB2 <= 10')
#validate = validate.query('SUB1 <= 10').query('SUB2 <= 10')

drop_list = ['DSMCRIT', 'STFIPS', 
             'ALCFLG', 'COKEFLG', 'MARFLG', 'HERFLG', 'METHFLG', 'OPSYNFLG', 'PCPFLG', 'HALLFLG', 'MTHAMFLG', 
             'AMPHFLG', 'STIMFLG', 'BENZFLG', 'TRNQFLG', 'BARBFLG', 'SEDHPFLG', 'INHFLG', 'OTCFLG', 'OTHERFLG', 
             'ALCDRUG', 
             ]

X_train = train.drop(drop_list, axis=1)
Y_train = train["DSMCRIT"]
X_validate = validate.drop(drop_list, axis=1)
Y_validate = validate["DSMCRIT"]
#X_test  = test.drop(drop_list, axis=1)
X_train.shape, X_validate.shape, #X_test.shape



((20000, 27), (6000, 27))

In [23]:
print X_train.columns.tolist()

['YEAR', 'AGE', 'GENDER', 'RACE', 'ETHNIC', 'MARSTAT', 'EDUC', 'EMPLOY', 'DETNLF', 'PREG', 'VET', 'LIVARAG', 'ARRESTS', 'SERVSETA', 'METHUSE', 'PSOURCE', 'DETCRIM', 'NOPRIOR', 'SUB1', 'ROUTE1', 'FREQ1', 'FRSTUSE1', 'SUB2', 'SUB3', 'NUMSUBS', 'IDU', 'PSYPROB']


In [24]:
#one hot
from sklearn import preprocessing

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(X_train)

# 3. Transform
onehotlabels = enc.transform(X_train).toarray()
#onehotlabels.shape
X_train = onehotlabels

onehotlabels = enc.transform(X_validate).toarray()
X_validate = onehotlabels

X_train.shape, X_validate.shape

((20000, 179), (6000, 179))

In [25]:
# Decision Tree

decision_tree = DecisionTreeClassifier(max_depth=20)
decision_tree.fit(X_train, Y_train)
#Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_validate, Y_validate) * 100, 2)
print acc_decision_tree
ts_acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
print ts_acc_decision_tree
#print cross_val_score(decision_tree, X_validate, Y_validate)

59.73
91.79


In [26]:
# Logistic Regression
logreg = LogisticRegression(n_jobs=-1)
logreg.fit(X_train, Y_train)
#Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_validate, Y_validate) * 100, 2)
print acc_log
ts_acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
print ts_acc_log
#print cross_val_score(logreg, X_validate, Y_validate)

/Users/arc/Codes/DM-Lab/dmlab/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


68.48
68.87


In [27]:
# Perceptron

perceptron = Perceptron(n_jobs=-1)
perceptron.fit(X_train, Y_train)
#Y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_validate, Y_validate) * 100, 2)
print acc_perceptron
ts_acc_perceptron = round(perceptron.score(X_train, Y_train) * 100, 2)
print ts_acc_perceptron
#print cross_val_score(perceptron, X_validate, Y_validate)

/Users/arc/Codes/DM-Lab/dmlab/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


57.65
58.13


In [29]:
# Random Forest (slow)

random_forest = RandomForestClassifier(n_estimators=100, n_jobs=-1, max_depth=20)
random_forest.fit(X_train, Y_train)
#Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, Y_train)
acc_random_forest = round(random_forest.score(X_validate, Y_validate) * 100, 2)
print acc_random_forest
ts_acc_random_forest = round(random_forest.score(X_train, Y_train) * 100, 2)
print ts_acc_random_forest

#print cross_val_score(random_forest, X_validate, Y_validate)

68.62
91.18


In [30]:
# 2-nn
knn = KNeighborsClassifier(n_neighbors = 2, n_jobs=-1)
knn.fit(X_train, Y_train)
#Y_pred = knn.predict(X_test)
acc_2nn = round(knn.score(X_validate, Y_validate) * 100, 2)
print acc_2nn
ts_acc_2nn = round(knn.score(X_train, Y_train) * 100, 2)
print ts_acc_2nn
#print cross_val_score(knn, X_validate, Y_validate)

49.85
73.93


In [31]:
# Stochastic Gradient Descent

sgd = SGDClassifier(n_jobs=-1)
sgd.fit(X_train, Y_train)
#Y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_validate, Y_validate) * 100, 2)
print acc_sgd
ts_acc_sgd = round(sgd.score(X_train, Y_train) * 100, 2)
print ts_acc_sgd
#print cross_val_score(sgd, X_validate, Y_validate)

/Users/arc/Codes/DM-Lab/dmlab/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


63.93
63.87


In [32]:
# Linear SVC
linear_svc = LinearSVC(C=0.5)
linear_svc.fit(X_train, Y_train)
#Y_pred = linear_svc.predict(X_test)

acc_linear_svc = round(linear_svc.score(X_train, Y_train) * 100, 2)
print acc_linear_svc
ts_acc_linear_svc = round(linear_svc.score(X_validate, Y_validate) * 100, 2)
print ts_acc_linear_svc


67.97
67.55


In [41]:
print 'predict-dsm-woflags-newsplit-sample20000'
models = pd.DataFrame({
    'Model': [ '2-NN', 'Logistic Regression', 
              'Random Forest', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVM', 
              'Decision Tree'],
    
    'Validation Set Accuracy': [ acc_2nn, acc_log, 
              acc_random_forest, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree],
        
    'Training Error': [100 - item for item in [ts_acc_2nn, ts_acc_log, 
              ts_acc_random_forest, ts_acc_perceptron, 
              ts_acc_sgd, ts_acc_linear_svc, ts_acc_decision_tree]],
    })
models.sort_values(by='Validation Set Accuracy', ascending=False)


predict-dsm-woflags-newsplit-sample20000


Model  Training Error  Validation Set Accuracy
2               Random Forest            8.82                    68.62
1         Logistic Regression           31.13                    68.48
5                  Linear SVM           32.45                    67.97
4  Stochastic Gradient Decent           36.13                    63.93
6               Decision Tree            8.21                    59.73
3                  Perceptron           41.87                    57.65
0                        2-NN           26.07                    49.85

In [50]:
Y_pred = linear_svc.predict(X_validate)


from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_validate, Y_pred, labels=[3,4,5,6,7,8,9,10])

import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = cm #confusion_matrix(y_test, Y_pred)
#class_names = ["ANXIETY","DEPRESS","SCHIZOPHRENIA","BIPOLAR","ATTENTION DEFICIT"]
class_names = [3,4,5,6,7,8,9,10]
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, class_names,
                      title='Confusion matrix, without normalization')
plt.savefig('cnf matrix', dpi=150)

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

#plt.figure(figsize=(16,8))
plt.savefig('cnf matrix norm', dpi=150)

Confusion matrix, without normalization
[[ 517   55    0    1    0    0    2    0]
 [  66 1094   10   23   21    8   57    0]
 [   0   18 1079    9   11    9    1    5]
 [   0   22    9  249   30    3    0    9]
 [   0   19   12    7  433    9    6  114]
 [   2   80  101   29   57  311    3    3]
 [  27  246    1    4   13    9  129    4]
 [   0   14    5    8  144    0    3  231]]
Normalized confusion matrix
[[  8.99e-01   9.57e-02   0.00e+00   1.74e-03   0.00e+00   0.00e+00
    3.48e-03   0.00e+00]
 [  5.16e-02   8.55e-01   7.82e-03   1.80e-02   1.64e-02   6.25e-03
    4.46e-02   0.00e+00]
 [  0.00e+00   1.59e-02   9.53e-01   7.95e-03   9.72e-03   7.95e-03
    8.83e-04   4.42e-03]
 [  0.00e+00   6.83e-02   2.80e-02   7.73e-01   9.32e-02   9.32e-03
    0.00e+00   2.80e-02]
 [  0.00e+00   3.17e-02   2.00e-02   1.17e-02   7.22e-01   1.50e-02
    1.00e-02   1.90e-01]
 [  3.41e-03   1.37e-01   1.72e-01   4.95e-02   9.73e-02   5.31e-01
    5.12e-03   5.12e-03]
 [  6.24e-02   5.68e-01   2.3